(lambda ()
  (spawn-label (- (/ (get-screen-width) 2) 640) 100 "maildaemon" 16.0)
  (spawn-image (- (/ (get-screen-width) 2) 500)
               (- (/ (get-screen-height) 2) 100)
               "textures/ampersand.png")
  (spawn-image (+ (/ (get-screen-width) 2) 180)
               (- (/ (get-screen-height) 2) 100)
               "textures/ampersand.png")
  (spawn-button
    (- (/ (get-screen-width) 2) 100)
    (- (/ (get-screen-height) 2) 100)
    "enter" (lambda ()
              (schedule
                (lambda ()
                  (reset-gui)
                  (set-mode "main"))
                0)))
  (spawn-button
    (- (/ (get-screen-width) 2) 100)
    (- (/ (get-screen-height) 2) 25)
    "quit" (lambda () (set-running #f))))
