(define SAFEZONE (build-entity-prototype "safezone" 32 32 0 0 0))
(set-entity-collideable SAFEZONE #f)
(set-entity-init SAFEZONE (lambda (e) 0))
(set-entity-hit SAFEZONE (lambda (e dmg data) data))
(set-entity-collide SAFEZONE (lambda (e data) (display "collide") (newline) data))
(set-entity-update SAFEZONE (lambda (e data)
                              (if (zero? data)
                                (let ((t (get-entity-texture e)))
                                 (set-sheet-column t (modulo (+ (get-sheet-column t) 1) 2))
                                 5)
                                (- data 1))))

(define (fill-safezone x0 y0 x1 y1)
  (let yloop ((y (* y0 32)))
   (if (<= y (* y1 32))
     (let xloop ((x (* x0 32)))
      (if (<= x (* x1 32))
        (begin
          (spawn-entity (make-entity "safezone" x y))
          (xloop (+ x 32))))
      (yloop (+ y 32))))))
