(let xloop ([xl (iota 20)])
 (display "test")
 (newline)
 (if (not (null? xl))
   (begin
     (let yloop ([yl (iota 20)])
      (if (not (null? yl))
        (begin
          (display (car xl))
          (display ", ")
          (display (car yl))
          (newline)
          (if (or (= (car yl) 0) (= (car yl) 19)) (set-tile (car xl) (car yl) 8))
          (if (or (= (car xl) 0) (= (car xl) 19)) (set-tile (car xl) (car yl) 9))
          (yloop (cdr yl)))))
     (xloop (cdr xl)))))
